project:
  type: website
  output-dir: _site
  resources:
    - fonts
  render:
    - index.qmd
    - cv/cv.qmd

website:
  title: "Joseph Bulbulia"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: CV
        href: cv/cv.qmd
    right:
      - icon: github
        href: https://github.com/go-bayes
      - icon: envelope
        href: mailto:joseph.bulbulia@vuw.ac.nz

format:
  html:
    respect-user-color-scheme: true
    theme:
      light: flatly
      dark: darkly
    css: styles/accept.css
    toc: true
    code-copy: true
    link-external-newwindow: true
