[build]
command = "if [ ! -d \"$HOME/quarto/quarto-${QUARTO_VERSION}\" ]; then mkdir -p \"$HOME/quarto\"; curl -L \"https://github.com/quarto-dev/quarto-cli/releases/download/v${QUARTO_VERSION}/quarto-${QUARTO_VERSION}-linux-amd64.tar.gz\" | tar -xz -C \"$HOME/quarto\"; fi && if [ ! -d \"$HOME/.TinyTeX\" ]; then \"$HOME/quarto/quarto-${QUARTO_VERSION}/bin/quarto\" install tinytex --no-prompt; fi && \"$HOME/quarto/quarto-${QUARTO_VERSION}/bin/quarto\" render"
publish = "_site"

[build.environment]
QUARTO_VERSION = "1.5.57"
